
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "arango/handler/handler.zep.h"
#include "arango/exception/exception.zep.h"
#include "arango/document/document.zep.h"
#include "arango/handler/documenthandler.zep.h"
#include "arango/http/executerequest.zep.h"
#include "arango/http/request.zep.h"
#include "arango/policies/policy.zep.h"
#include "arango/batch/batch.zep.h"
#include "arango/batch/batchpart.zep.h"
#include "arango/client/configuration.zep.h"
#include "arango/collection/collection.zep.h"
#include "arango/connection/connection.zep.h"
#include "arango/connection/encoding.zep.h"
#include "arango/connection/endpoint.zep.h"
#include "arango/connection/options.zep.h"
#include "arango/connection/tracerequest.zep.h"
#include "arango/connection/traceresponse.zep.h"
#include "arango/cursor/cursor.zep.h"
#include "arango/cursor/exportcursor.zep.h"
#include "arango/database/database.zep.h"
#include "arango/document/edge.zep.h"
#include "arango/document/vertex.zep.h"
#include "arango/exception/clientexception.zep.h"
#include "arango/exception/connectionexception.zep.h"
#include "arango/exception/serverexception.zep.h"
#include "arango/export/export.zep.h"
#include "arango/graph/graph.zep.h"
#include "arango/graph/traversal.zep.h"
#include "arango/handler/adminhandler.zep.h"
#include "arango/handler/collectionhandler.zep.h"
#include "arango/handler/edgehandler.zep.h"
#include "arango/handler/querycachehandler.zep.h"
#include "arango/handler/queryhandler.zep.h"
#include "arango/handler/vertexhandler.zep.h"
#include "arango/http/api.zep.h"
#include "arango/http/client.zep.h"
#include "arango/http/response.zep.h"
#include "arango/http/url.zep.h"
#include "arango/policies/updatepolicy.zep.h"
#include "arango/query/statement.zep.h"
#include "arango/transaction/transaction.zep.h"
#include "arango/validation/bind.zep.h"
#include "arango/validation/validation.zep.h"

#endif