arango.lo: /home/lucas/Code/arangodb-php-driver/ext/arango.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango.c -o arango.lo 
kernel/main.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/lucas/Code/arangodb-php-driver/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/kernel/exit.c -o kernel/exit.lo 
arango/handler/handler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/handler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/handler.zep.c -o arango/handler/handler.lo 
arango/exception/exception.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/exception/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/exception/exception.zep.c -o arango/exception/exception.lo 
arango/document/document.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/document/document.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/document/document.zep.c -o arango/document/document.lo 
arango/handler/documenthandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/documenthandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/documenthandler.zep.c -o arango/handler/documenthandler.lo 
arango/http/executerequest.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/executerequest.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/executerequest.zep.c -o arango/http/executerequest.lo 
arango/http/request.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/request.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/request.zep.c -o arango/http/request.lo 
arango/policies/policy.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/policies/policy.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/policies/policy.zep.c -o arango/policies/policy.lo 
arango/batch/batch.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/batch/batch.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/batch/batch.zep.c -o arango/batch/batch.lo 
arango/batch/batchpart.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/batch/batchpart.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/batch/batchpart.zep.c -o arango/batch/batchpart.lo 
arango/client/configuration.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/client/configuration.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/client/configuration.zep.c -o arango/client/configuration.lo 
arango/collection/collection.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/collection/collection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/collection/collection.zep.c -o arango/collection/collection.lo 
arango/connection/connection.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/connection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/connection.zep.c -o arango/connection/connection.lo 
arango/connection/encoding.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/encoding.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/encoding.zep.c -o arango/connection/encoding.lo 
arango/connection/endpoint.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/endpoint.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/endpoint.zep.c -o arango/connection/endpoint.lo 
arango/connection/options.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/options.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/options.zep.c -o arango/connection/options.lo 
arango/connection/tracerequest.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/tracerequest.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/tracerequest.zep.c -o arango/connection/tracerequest.lo 
arango/connection/traceresponse.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/connection/traceresponse.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/connection/traceresponse.zep.c -o arango/connection/traceresponse.lo 
arango/cursor/cursor.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/cursor/cursor.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/cursor/cursor.zep.c -o arango/cursor/cursor.lo 
arango/cursor/exportcursor.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/cursor/exportcursor.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/cursor/exportcursor.zep.c -o arango/cursor/exportcursor.lo 
arango/database/database.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/database/database.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/database/database.zep.c -o arango/database/database.lo 
arango/document/edge.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/document/edge.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/document/edge.zep.c -o arango/document/edge.lo 
arango/document/vertex.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/document/vertex.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/document/vertex.zep.c -o arango/document/vertex.lo 
arango/exception/clientexception.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/exception/clientexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/exception/clientexception.zep.c -o arango/exception/clientexception.lo 
arango/exception/connectionexception.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/exception/connectionexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/exception/connectionexception.zep.c -o arango/exception/connectionexception.lo 
arango/exception/serverexception.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/exception/serverexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/exception/serverexception.zep.c -o arango/exception/serverexception.lo 
arango/export/export.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/export/export.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/export/export.zep.c -o arango/export/export.lo 
arango/graph/graph.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/graph/graph.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/graph/graph.zep.c -o arango/graph/graph.lo 
arango/graph/traversal.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/graph/traversal.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/graph/traversal.zep.c -o arango/graph/traversal.lo 
arango/handler/adminhandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/adminhandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/adminhandler.zep.c -o arango/handler/adminhandler.lo 
arango/handler/collectionhandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/collectionhandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/collectionhandler.zep.c -o arango/handler/collectionhandler.lo 
arango/handler/edgehandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/edgehandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/edgehandler.zep.c -o arango/handler/edgehandler.lo 
arango/handler/querycachehandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/querycachehandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/querycachehandler.zep.c -o arango/handler/querycachehandler.lo 
arango/handler/queryhandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/queryhandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/queryhandler.zep.c -o arango/handler/queryhandler.lo 
arango/handler/vertexhandler.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/handler/vertexhandler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/handler/vertexhandler.zep.c -o arango/handler/vertexhandler.lo 
arango/http/api.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/api.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/api.zep.c -o arango/http/api.lo 
arango/http/client.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/client.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/client.zep.c -o arango/http/client.lo 
arango/http/response.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/response.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/response.zep.c -o arango/http/response.lo 
arango/http/url.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/http/url.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/http/url.zep.c -o arango/http/url.lo 
arango/policies/updatepolicy.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/policies/updatepolicy.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/policies/updatepolicy.zep.c -o arango/policies/updatepolicy.lo 
arango/query/statement.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/query/statement.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/query/statement.zep.c -o arango/query/statement.lo 
arango/transaction/transaction.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/transaction/transaction.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/transaction/transaction.zep.c -o arango/transaction/transaction.lo 
arango/validation/bind.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/validation/bind.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/validation/bind.zep.c -o arango/validation/bind.lo 
arango/validation/validation.lo: /home/lucas/Code/arangodb-php-driver/ext/arango/validation/validation.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lucas/Code/arangodb-php-driver/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lucas/Code/arangodb-php-driver/ext/arango/validation/validation.zep.c -o arango/validation/validation.lo 
$(phplibdir)/arango.la: ./arango.la
	$(LIBTOOL) --mode=install cp ./arango.la $(phplibdir)

./arango.la: $(shared_objects_arango) $(ARANGO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_arango) $(ARANGO_SHARED_LIBADD)

